### ISSUE TITLE
vue компоненты

### ISSUE THREAD

**Issue by MasterOfDeath** [bitrix-tools/cli#1]
Есть возможность использовать компоненты *.vue ?
На сколько я вижу вы используете rollup, есть ли какая то возможно сть использовать плагин для однофайловых компонентов vue, например вот этот: https://github.com/vuejs/rollup-plugin-vue

**Comment by vovkabelov** [comment]
@MasterOfDeath, да, вы можете собирать `*.vue` компоненты с помощью @bitrix/cli. 
Эта возможность доступна с версии @bitrix/cli@2.1.13 — в этой версии добавлена возможность использовать произвольные Rollup плагины. 

Чтобы заработала сборка `*.vue` компонентов нужно: 
1. Установить последнюю версию @bitrix/cli 
`npm install -g @bitrix/cli`
2. Установить `rollup-plugin-vue`, `rollup-plugin-commonjs` и `vue-template-compiler`
`npm install rollup-plugin-vue rollup-plugin-commonjs vue-template-compiler`
3. В `bundle.config.js` указать использование установленных плагинов
```
const vuePlugin = require('rollup-plugin-vue');
const commonjs = require('rollup-plugin-commonjs');

module.exports = {
	input: 'src/app.js',
	output: 'dist/app.bundle.js',
	namespace: 'BX.MyApp',
	plugins: {
		custom: [
			commonjs(),
			vuePlugin(),
		],
	},
};
```

Обратите внимание, что `rollup-plugin-commonjs` и `vue-template-compiler` нужны для корректой работы `rollup-plugin-vue`. https://rollup-plugin-vue.vuejs.org/faqs.html

**Comment by sup2007** [comment]
также стоит обратить внимание что при использовании опции `resolve: true` плагин `rollup-plugin-commonjs` будет подключен "автоматом", если не был подключен ранее.

**Comment by vadikgr-hub** [comment]
При выполнении команды bitrix build --watch пишет
`    Error: Insufficient Rollup version: "rollup-plugin-commonjs" requires at least rollup@1.12.0 but found rollup@0.67.4.`
При установке rollup-plugin-commonjs пишет что он deprecated и предлагает установить @rollup/plugin-commonjs

Если установить @rollup/plugin-commonjs и поставить в bundle.config.js const commonjs = require('@rollup/plugin-commonjs'); то появляется Error: this.resolve is not a function

Как же побороть это?

**Comment by wett1988** [comment]
> Как же побороть это?

Если в команде `npm install rollup-plugin-commonjs` не указывать версию, то установится самая последняя версия. Откатитесь на предыдущую версию `rollup-plugin-commonjs` и перезапустите установку пакетов.

Я прописал в package.json `"rollup-plugin-commonjs": "^9.0.0"` и `bitrix build` прошел без ошибки.

**Comment by devjob** [comment]
А можно пример -как регистрировать однофайловые компоненты?
BX.Vue.component - не поддерживает такое?

**Comment by ennuiby** [comment]
> А можно пример -как регистрировать однофайловые компоненты? BX.Vue.component - не поддерживает такое?

например в экстеншене.
