### ISSUE TITLE
Ошибки при установке

### ISSUE THREAD

**Issue by natskazak** [bitrix-tools/cli#10]
Не получается выполнить установку, в чем может быть проблема?

<img width="1114" alt="Без названия" src="https://user-images.githubusercontent.com/28258551/68650855-6ee80780-053f-11ea-8a4f-fb9c8ee12680.png">

**Comment by vovkabelov** [comment]
@natskazak, сейчас у некоторых пользователей может наблюдаться проблема с компиляцией одного из пакетов входящих в состав @bitrix/cli. Как вариант временного решения — это установить предыдущую версию @bitrix/cli. 

Попробуйте выполнить установку командой:  
`npm install -g @bitrix/cli@2.3.1`

**Comment by natskazak** [comment]
✈️Взлетело. Спасибо большое!
