### ISSUE TITLE
ошибка при подключении плагина

### ISSUE THREAD

**Issue by kd241286zjv** [bitrix-tools/cli#11]
добрый день!
в компоненте импортирую
import Datepicker from 'vuejs-datepicker';

добавляю в разметку
<Datepicker/>

экспортирую
components: {
  Datepicker
}

после сборки получаю в консоли ошибку
Uncaught TypeError: Cannot read property '__esModule' of undefined

файл bundle.config.js:
module.exports = {
	input: 'src/default-component.js',
	output: 'dist/default-component.bundle.js',
	plugins: {
		resolve: true,
	},
};

что делаю не так?

**Comment by vovkabelov** [comment]
@kd241286zjv, посмотрел. У меня воспроизвести не получилось. Проверял так: 

bundle.config.js
```
module.exports = {
	input: 'src/datepicker.js',
	output: 'dist/datepicker.bundle.js',
	plugins: {
		resolve: true,
	},
};
```

src/datepicker.js
```
import Datepicker from 'vuejs-datepicker';

const components = {
	Datepicker,
};

export {
	components,
};
```

index.php
```
<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Sandbox");

\Bitrix\Main\UI\Extension::load([
	'mymodule.datepicker',
]);
?>
<script src="https://unpkg.com/vue"></script>

<div id="app">
	<vuejs-datepicker></vuejs-datepicker>
</div>

<script>
	const app = new Vue({
		el: '#app',
		components: {
			vuejsDatepicker: components.Datepicker,
		}
	})
</script>

<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");
```
