### ISSUE TITLE
поддержка отслеживания изменений файлов с расширением  .vue 

### ISSUE THREAD

**Issue by sup2007** [bitrix-tools/cli#13]
```js
import MyCustomComponent from './my-custom-component.vue'
```

далее

```
bitrix build -w
```

При изменении файла `my-custom-component.vue` сборщик "молчит" он не видит изменений файла.

Сейчас расширения для отслеживания "зашиты" (hardcoded) в приложении. Если есть возможность использовать `.vue` файлы, значит **необходимо добавить поддержку** `--watch` для этих расширений. 

> в качестве эксперимента добавили опцию для указания расширения и добавили `.vue` в [в is-allowed.js](https://github.com/bitrix-tools/cli/blob/016606fce31f67f7871a1a219b69c1f9d917b95d/src/utils/is-allowed.js#L23). Работает. 

Может есть развернутая информация, или ограничения?

#1

**Comment by gbublik** [comment]
> ```js
> import MyCustomComponent from './my-custom-component.vue'
> ```
> 
> далее
> 
> ```
> bitrix build -w
> ```
> 
> При изменении файла `my-custom-component.vue` сборщик "молчит" он не видит изменений файла.
> 
> Сейчас расширения для отслеживания "зашиты" (hardcoded) в приложении. Если есть возможность использовать `.vue` файлы, значит **необходимо добавить поддержку** `--watch` для этих расширений.
> 
> > в качестве эксперимента добавили опцию для указания расширения и добавили `.vue` в [в is-allowed.js](https://github.com/bitrix-tools/cli/blob/016606fce31f67f7871a1a219b69c1f9d917b95d/src/utils/is-allowed.js#L23). Работает.
> 
> Может есть развернутая информация, или ограничения?
> 
> #1

А это вообще работает ? у меня import vue файлов возвращает битриксовскую функцию вообще

**Comment by frusanov** [comment]
За одно бы тогда и .ts и .tsx добавить
