### ISSUE TITLE
Неверное определение кодировки при наличии в исходниках кириллических символов

### ISSUE THREAD

**Issue by grudolobichdeleted** [bitrix-tools/cli#16]
В файле src\tools\build\adjust-encoding.js
имеется определение кодировки
`
export function getEncoding(buffer)
{
	const result = jscharder.detect(buffer);

	if (!result || result.encoding === 'UTF-8')
	{
		return 'utf-8';
	}

	return 'windows-1251';
}
`
Которое приводит к сохранению в кодировке windows 1251, при наличии кириллических символов в исходниках

Минимальный фикс этой проблемы оформлен в PR: #15

**Comment by sup2007** [comment]
также обсуждалось в #2

**Comment by akaSpy** [comment]
Проблема до сих пор имеет место быть.
