### ISSUE TITLE
vue кодировка текста или поддержка русского языка

### ISSUE THREAD

**Issue by astrahov** [bitrix-tools/cli#2]
const vuePlugin = require('rollup-plugin-vue');
const commonjs  = require('rollup-plugin-commonjs');

module.exports = {
    //...
    plugins: {
        custom: [
            commonjs(),
            vuePlugin(),
        ],
    },
};

Плагины подключены, *.vue файлы поддерживаются, js компилируется. Но проблема в русском языке. Если во vue файле есть русский язык, то в скомпилированном js будут знаки вопроса вместо русского языка. С английским текстом все в норме. Кодировка всех файлов UTF-8

**Comment by astrahov** [comment]
#3

**Comment by vovkabelov** [comment]
@astrahov, поправили. Переустановите @bitrix/cli (`npm install -g @bitrix/cli`), с кодировкой больше не должно быть проблем

**Comment by astrahov** [comment]
Оборудование: MacBook Pro 2017 13", OS X Mojave 10.14.4.
@bitrix/cli 2.1.14

Для дебага добавил `console.log()` в функцию `getEncoding()` в файле **bitrix.build.js**

```
function getEncoding(buffer) {
  const result = jscharder.detect(buffer);

  console.log(buffer);

  if (!result || result.encoding === 'UTF-8') {
    return 'utf-8';
  }

  return 'windows-1251';
}
```

После этого выполнил `bitrix build`

Консоль:
```
{ encoding: 'ascii', confidence: 1 }
{ encoding: 'UTF-8', confidence: 0.99 }
```

И согласно условию внутри функции в первом случае функция вернет **windows-1251**, а во втором случае **utf-8**. А нужно, чтобы в обоих случаях возвращала **utf-8**.

Ошибка не исправлена. Вместо русских символов вопросы.

**Comment by vovkabelov** [comment]
@astrahov, добавил ваш pull request в @bitrix/cli@2.1.16. Обновите @bitrix/cli, проверьте, должно работать.

**Comment by velsi** [comment]
Потерялся этот pull request - до сих пор проблемы с кодировкой.
Как временное решение вставить любой русский текст в файл input

**Comment by sup2007** [comment]
`cli` пытается  [автоматически определять кодировку](https://github.com/bitrix-tools/cli/blob/016606fce31f67f7871a1a219b69c1f9d917b95d/src/tools/build/adjust-encoding.js#L7) через `jscharder`.  И поэтому мы видим `{ encoding: 'ascii', confidence: 1 }` если во входящем файле нет "utf" символов. 

Теперь если мы напишем в файле, да например просто в комментарии 

```js
/**
  * теперь это файл/поток будет кодироваться в UTF-8
  */
```
то получим примерно такой вывод от `jscharder`

```js
{ encoding: 'UTF-8', confidence: 0.99 }
```
и весь поток будет перекодирован в `utf-8`.

ps. Думаю, можно было бы добавить опции для принудительной конвертации в utf-8, для определения расширений в графе зависимостей, для подобных случаев (в данном контексте, это файлы `*.vue`). Но кодировать всё в utf-8  по умолчанию, наверное это не то. Пока не  смогу сказать какие еще есть варианты с Rollup (может есть опции) или Buffer, но предложенный выше эксперимент работает с `.vue` файлами, контент кодируется и отображается правильно.
