### ISSUE TITLE
В тестах не работает resolver при подключении других extension-ов

### ISSUE THREAD

**Issue by pr0n1x** [bitrix-tools/cli#33]
Например есть два extension-а:
- vend.commerce-targets (namespace: `vend.mod.commerce_targets`)
- vend.logger (namespace: `vend.mod.logger`)

Допустим мы подключаем в одном из файлов `vend.mod.commerce-targets` зависимость через import  
файл `/local/js/vend/mod/commerce-targets/src/services/TargetService.js`:  
```js
import Logger 'vend.mod.logger';

export class TargetService
{
  targets = [];
  logger = Logger.getInstance();
  // ...
}
```

В таком случае в браузере будут внутри объекты
`vend.mod.logger` и `vend.mod.commerce_targets`
и все будет корректно (о подгрузке второго extension-а позаботится Битрикс) ибо зависимость автоматом влетает в config.php.

Внутри тестов же `import Logger 'vend.mod.logger';` обрабатывается некорректно и приходится вместо внешнего подключения зависимости включать зависимостьи венутрь бандла vend.commerce-targets
слудующим образом:  
```js
import Logger from '../../../logger/src/logger';


```  

В противном случае на тестах получаем ошибку обращения к пустому объекту.
В нашем случае она выглядит так
`(node:1211857) UnhandledPromiseRejectionWarning: TypeError: _assert.default.getInstance is not a function`

В данном примере проблема не велика, но если бы расширения были бы "пожирнее"... В общем закрывать глаза на проблему прям не получаеться

Код @bitrix/cli сами не вычитывали, но есть у нас гипотеза, что виноват даже не резольвер. Результат компиляции дла браузера включет в себя замыкание вида

```js
(function (exports,Logger) {
  /// ...
}((this.vend.mod.commerce_targets = this.vend.mod.commerce_targets || {}),vend.mod.logger));
```

Чутье подсказывает что проблема кроется где-то вокруг работы с `this` - но это тыкание пальцем в небо.

Вот ещё любопытный момент. Если написать так
```js
import Logger from 'vend.mod.logger';

export class TargetService
{
  // targets = [];
  // logger = Logger.getInstance();

  constructor() {
    console.dir(typeof Logger);
    console.dir(Logger.name);
    throw 'Stop here';
  }
```

Выдает вот такой результат. Очень похоже что import вернул нам какой-то объект **mocha** вместо нашего логгера.
```
function
ok
{ [Function: ok]
  fail: [Function: fail],
  AssertionError: [Function: AssertionError],
  ok: [Circular],
  equal: [Function: equal],
  notEqual: [Function: notEqual],
  deepEqual: [Function: deepEqual],
  notDeepEqual: [Function: notDeepEqual],
  deepStrictEqual: [Function: deepStrictEqual],
  notDeepStrictEqual: [Function: notDeepStrictEqual],
  strictEqual: [Function: strictEqual],
  notStrictEqual: [Function: notStrictEqual],
  ...
  
```

**Comment by pr0n1x** [comment]
Удалось обойти баг, но сие решение выглядит в коде чудовищно/некрасиво. Если станет кому интересно, могу описать.

**Comment by FoxMalder** [comment]
> Удалось обойти баг, но сие решение выглядит в коде чудовищно/некрасиво. Если станет кому интересно, могу описать.

Опиши, пожалуйста

**Comment by vovkabelov** [comment]
Исправлено в версии 3.2.0.
Пожалуйста, обновите @bitrix/cli, проблем с резолвингом экстеншнов в тестах больше быть не должно.
Обновить @bitrix/cli можно просто переустановив его командой `npm install -g @bitrix/cli`.
