### ISSUE TITLE
Сборка расширением с использованием однофайловых компонентов для bitrix/cli ^3.0.1

### ISSUE THREAD

**Issue by akellaweb** [bitrix-tools/cli#35]
Нужна актуальная информация / инструкция для последней версии bitrix/cli (3.0.3)

Как использовать его?

При использовании инструкции отсюда https://github.com/bitrix-tools/cli/issues/1 - была ошибка http://joxi.ru/82Q06k3t9LlPEm .

Пакеты обновились.
Установил последние пакеты - @rollup/plugin-commonjs , rollup-plugin-vue

`"dependencies": {
    "@rollup/plugin-commonjs": "^18.0.0",
    "rollup-plugin-vue": "^4.7.1"
  }`

Во время сборки bitrix build -w - вылетает ошибка . 

http://joxi.ru/12MEqOKIkV4dy2
типа @rollup/plugin-commonjs - требует минимум версию rollup пакета 2.30, но найдена версия 0.67.4.
Если проверить текущую версию в папке с расширениями - то видно, что версия другая установлена.
http://joxi.ru/n2Yb3Q7UeLj1MA

**Comment by akellaweb** [comment]
Разобрался.
Если у кого такая же проблема - переустановить пакет bitrix/cli и далее - все как в инструкции.

**Comment by extdesign** [comment]
> Если у кого такая же проблема - переустановить пакет bitrix/cli и далее - все как в инструкции.

Переустановил, но проблема осталось. При установке куча WARNингов.
Причем версия @bitrix/cli - 3.1.1

Заходить в пакет @bitrix/cli и внутри обновлять зависимости?

![Снимок экрана 2023-03-01 в 09 07 28](https://user-images.githubusercontent.com/56507999/222058842-549fe34f-13c3-4d03-bd54-5d81d9522286.png)

![Снимок экрана 2023-03-01 в 09 09 20](https://user-images.githubusercontent.com/56507999/222058983-15982ee3-5e97-4818-a377-db064951a357.png)

**Comment by akellaweb** [comment]
@extdesign , попробуй @rollup пакет глобально. 
После этого должно заработать.

![bitrix-cli-rollup](https://github.com/bitrix-tools/cli/assets/5145327/83e2370a-4007-4e0d-9f4b-b5dbc0555457)
