### ISSUE TITLE
bitrix/cli  неверная кодировка для кириллицы

### ISSUE THREAD

**Issue by shumiv** [bitrix-tools/cli#46]
Собираю ванильный ЖС с помощью bitrix/cli и не могу использовать кириллицу. Что делать? Вместо кириллицы знаки вопроса

**Comment by kavdeev** [comment]
он при сборке пытается угадать кодировку. лечится добавлением строчки типа
// просто текст чтобы bitrix cli правильно выставил кодировку
в любой js файл
