### ISSUE TITLE
Не работает импорт экстеншнов

### ISSUE THREAD

**Issue by nook-ru** [bitrix-tools/cli#6]
Возникает ошибка `Uncaught TypeError: xxx is not a constructor/function`

Воспроизвести можно так:

1. Создаем пару экстеншенов:

	```console

	$ mkdir -p ./local/js/partner/module && cd $_

	$ bitrix create ext1

	$ bitrix create ext2
	```

2. Добавляем в `ext2` импорт `ext1`:

	```diff
	--- a/local/js/partner/module/ext2/src/ext2.js
	+++ b/local/js/partner/module/ext2/src/ext2.js
	@@ -1,10 +1,13 @@
	 import {Type} from 'main.core';
	+import {Ext1} from "partner.module.ext1";
	 
	 export class Ext2
	 {
	        constructor(options = {name: 'Ext2'})
	        {
	                this.name = options.name;
	+
	+               this.ext1 = new Ext1();
	        }
	 
	        setName(name)
	```

3. `$ bitrix build -p .`

4. Подключаем:

	```php
	<?php

	\Bitrix\Main\UI\Extension::load(['partner.module.ext2']);
	?>
	<script>
	var ext2 = new BX.Partner.Module.Ext2();
	</script>

	```

Видим ошибку:

![image](https://user-images.githubusercontent.com/444489/59887182-fe432180-93ca-11e9-8907-a702aef98138.png)

**Comment by nook-ru** [comment]
Возможно как-то связано: тесты не проходят из-за import'ов даже на свежесозданном экстеншене:

```
(node:17071) UnhandledPromiseRejectionWarning: Error: Cannot find module 'main.core'
Require stack:
- /ext1/src/ext1.js
- /ext1/test/ext1/ext1.test.js
```

![image](https://user-images.githubusercontent.com/444489/59887654-e076bc00-93cc-11e9-8c86-3c5fcad20890.png)

**Comment by nook-ru** [comment]
В полученном бандле лучше видно откуда ошибка: вторым аргументом `partner_module_ext1` передается не тот неймспейс. Вместо BX должен передаваться BX.Partner.Module, наверное.

![image](https://user-images.githubusercontent.com/444489/59906430-69afe200-9411-11e9-836d-4ab4b1ef8193.png)

**Comment by vovkabelov** [comment]
@nook-ru, действительно, была ошибка при генерации неймспейса. Поправил. Обновите @bitrix/cli, должно заработать
