### ISSUE TITLE
Ошибка no such file or directory после команды bitrix build

### ISSUE THREAD

**Issue by procourt** [bitrix-tools/cli#8]
Что может быть не так?
Вот, что в консоли:

>   Replace Autoprefixer browsers option to Browserslist config.
>   Use browserslist key in package.json or .browserslistrc file.
> 
>   Using browsers option cause some error. Browserslist config 
>   can be used for Babel, Autoprefixer, postcss-normalize and other tools.
> 
>   If you really need to use option, rename it to overrideBrowserslist.
> 
>   Learn more at:
>   https://github.com/browserslist/browserslist#readme
>   https://twitter.com/browserslist
> 
>  × 19:50:13 Build bundle C:\testproject\dist1\local\test.bundle.js  js: 119 B
> (node:10328) UnhandledPromiseRejectionWarning: Error: Error: ENOENT: no such file or directory, open 'C:\Users\Vadik\AppData\Roaming\npm\node_modules\@bitrix\cli\src\templates\config.php'
>     at printError (C:\Users\Vadik\AppData\Roaming\npm\node_modules\@bitrix\cli\dist\bitrix.build.js:317:11)
>     at report (C:\Users\Vadik\AppData\Roaming\npm\node_modules\@bitrix\cli\dist\bitrix.build.js:410:3)
>     at buildDirectory (C:\Users\Vadik\AppData\Roaming\npm\node_modules\@bitrix\cli\dist\bitrix.build.js:707:7)
>     at <anonymous>
> (node:10328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
> (node:10328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>

**Comment by vovkabelov** [comment]
@procourt, обновите @bitrix/cli. Больше ошибки быть не должно. Исправлено в версии @bitrix/cli 2.2.7
