### ISSUE TITLE
Приходится указывать абсолютный путь до своих плагинов

### ISSUE THREAD

**Issue by alukard12rus** [bitrix-tools/cli#9]
При создании своего расширения, к примеру в папке /local/js/module_name то в файл config.php требуется указывать жестко путь до корня сайта. Если этого не делать, то расширение не подключается с помощью Bitrix\Main\Ui\Extension::load

Есть ли возможность это пофиксить или я что то делаю не та?

**Comment by vovkabelov** [comment]
@alukard12rus, подскажите, по какому пути у вас расположено расширение (можно указать относительный путь до config.php) и какая версия "Главного модуля"?

Я проверил у себя — подключается корректно. 

Проверял так 
1. Создал расширение `/local/js/test/app` 
2. В config.php указал относительные пути 
3. Подключил на страницу `\Bitrix\Main\UI\Extension::load('test.app')`

**Comment by alukard12rus** [comment]
@vovkabelov, спасибо большое за информацию. В 18 версии ядра такая ошибка наблюдается. Обновил до 19.0.10000 больше такой ошибки нет
